# Generated by Django 3.1.3 on 2021-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='media/userimage/hi.png', null=True, upload_to='media/userimage'),
        ),
    ]
