# Generated by Django 3.1.3 on 2021-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210213_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='media/userimage/hi.png', upload_to='media/userimage'),
        ),
    ]
