# Generated by Django 3.1.3 on 2021-01-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmaticitems',
            name='measure',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'Kg'), ('3', 'Liter')], default=1, max_length=30),
        ),
    ]
