# Generated by Django 3.1.3 on 2021-01-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatic', '0002_cosmaticitems_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmaticitems',
            name='measure1',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
