# Generated by Django 3.1.3 on 2021-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatic', '0003_cosmaticitems_measure1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmaticitems',
            name='maxlimit',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
