# Generated by Django 3.1.3 on 2021-02-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatic', '0004_cosmaticitems_maxlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmaticitems',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
