# Generated by Django 3.1.3 on 2021-02-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatic', '0005_cosmaticitems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmaticitems',
            name='cosPrice',
            field=models.FloatField(),
        ),
    ]
