# Generated by Django 3.1.3 on 2021-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatic', '0006_auto_20210202_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmaticitems',
            name='description',
            field=models.TextField(blank=True, default='No Description Available for this product'),
        ),
    ]
