# Generated by Django 3.1.3 on 2021-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatic', '0007_auto_20210203_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmaticitems',
            name='minlimit',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cosmaticitems',
            name='specialuri',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
