# Generated by Django 3.1.3 on 2021-01-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpveification1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('otp', models.IntegerField(blank=True, default=0)),
                ('number_trial', models.IntegerField(blank=True, default=0)),
                ('timestamps', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
