# Generated by Django 3.1.3 on 2021-08-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Items1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_items', models.CharField(max_length=150)),
                ('items', models.CharField(max_length=150)),
                ('price', models.FloatField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RestroAccount1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=70)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('tk', models.CharField(blank=True, max_length=70, unique=True)),
                ('image', models.ImageField(default='media/userimage/hi.png', upload_to='media/userimage')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date-joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last-joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('unique_tag', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Store1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=10000)),
                ('table_no', models.CharField(max_length=100)),
            ],
        ),
    ]
