# Generated by Django 3.1.3 on 2021-08-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories1',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Items1',
            new_name='Items',
        ),
        migrations.RenameModel(
            old_name='RestroAccount1',
            new_name='RestroAccount',
        ),
        migrations.RenameModel(
            old_name='Store1',
            new_name='Store',
        ),
    ]
