# Generated by Django 3.1.3 on 2021-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_auto_20210820_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousStoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=200)),
                ('table_data', models.CharField(max_length=10000)),
                ('table_no', models.CharField(max_length=100)),
                ('order_taker', models.CharField(max_length=100)),
                ('net_amount', models.FloatField()),
                ('time', models.CharField(max_length=150)),
            ],
        ),
    ]
