# Generated by Django 3.1.3 on 2021-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_previousstoredata'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroaccount',
            name='firebasetk',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
