# Generated by Django 3.1.3 on 2021-09-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0004_restroaccount_firebasetk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restroaccount',
            name='firebasetk',
            field=models.CharField(max_length=150),
        ),
    ]
