# Generated by Django 3.1.3 on 2021-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0006_auto_20210924_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restroaccount',
            name='firebasetk',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
