# Generated by Django 3.1.3 on 2021-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devicetoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.FloatField(blank=True, null=True)),
                ('number', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
