# Generated by Django 3.1.3 on 2021-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='fcm_token',
            field=models.CharField(default='hellow', max_length=400),
        ),
    ]
