# Generated by Django 3.1.3 on 2021-02-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BagAdding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosQuantity', models.IntegerField()),
                ('cosToken', models.CharField(blank=True, max_length=70)),
                ('measure', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
