# Generated by Django 3.1.3 on 2021-02-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_auto_20210204_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosBrand', models.CharField(max_length=70)),
                ('cosName', models.CharField(max_length=70)),
                ('cosPrice', models.FloatField()),
                ('cosDis', models.FloatField(blank=True, max_length=30, null=True)),
                ('cosQuantity', models.IntegerField()),
                ('cosImage1', models.ImageField(blank=True, upload_to='media/cosmaticimages/')),
                ('cosToken', models.CharField(blank=True, max_length=70)),
                ('measure', models.CharField(choices=[('1', 'normal'), ('2', 'Kg'), ('3', 'Liter')], default=1, max_length=30)),
                ('Quantityorder', models.FloatField()),
                ('number', models.CharField(max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='bagadding',
            old_name='measure',
            new_name='number',
        ),
    ]
