# Generated by Django 3.1.3 on 2021-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_auto_20210205_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitems',
            name='Quantityorder',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
