# Generated by Django 3.1.3 on 2021-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0006_auto_20210205_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosBrand', models.CharField(max_length=70)),
                ('cosName', models.CharField(max_length=70)),
                ('cosPrice', models.FloatField()),
                ('cosDis', models.FloatField(blank=True, max_length=30, null=True)),
                ('cosQuantity', models.IntegerField()),
                ('cosImage1', models.ImageField(blank=True, upload_to='media/cosmaticimages2/')),
                ('cosToken', models.CharField(blank=True, max_length=70)),
                ('measure', models.CharField(choices=[('1', 'normal'), ('2', 'Kg'), ('3', 'Liter')], default=1, max_length=30)),
                ('Quantityorder', models.FloatField(blank=True, null=True)),
                ('number', models.CharField(max_length=70)),
                ('order', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Item Out of Stock', 'Item Out of Stock'), ('Order Confirmed', 'Order Confirmed'), ('In Processes', 'In Processes'), ('Delivered', 'Delivered')], default='In Processes', max_length=30)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
