# Generated by Django 3.1.3 on 2021-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0007_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cosImage1',
            field=models.ImageField(blank=True, upload_to='media/cosmaticimages/'),
        ),
    ]
