# Generated by Django 3.1.3 on 2021-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0008_auto_20210212_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitems',
            name='cosImage1',
            field=models.ImageField(blank=True, upload_to='cosmaticimages/'),
        ),
    ]
