# Generated by Django 3.1.3 on 2021-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0011_auto_20210212_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulloreder', models.TextField(blank=True)),
            ],
        ),
    ]
