# Generated by Django 3.1.3 on 2021-04-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0012_fullorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullorder',
            old_name='fulloreder',
            new_name='fullorder',
        ),
    ]
