# Generated by Django 3.1.3 on 2020-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdasboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('switch', models.BooleanField(default=False)),
                ('identity', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
