# Generated by Django 3.1.3 on 2021-03-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdasboard', '0002_auto_20210112_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdasboard',
            name='itemname',
            field=models.ImageField(blank=True, upload_to='media/userdasboardtitle/'),
        ),
    ]
