# Generated by Django 3.1.3 on 2021-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdasboard', '0003_auto_20210314_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdasboard',
            name='identity',
            field=models.CharField(choices=[('1', 'None'), ('2', 'structure1'), ('3', 'structure2'), ('4', 'structure3'), ('5', 'structure4'), ('6', 'structure5'), ('7', 'structure6'), ('8', 'structure7'), ('9', 'structure8')], max_length=30),
        ),
    ]
