# Generated by Django 3.1.3 on 2021-04-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdasboard', '0004_auto_20210314_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdasboard',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
