# Generated by Django 3.1.3 on 2020-12-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerposter',
            name='url',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
