# Generated by Django 3.1.3 on 2021-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0002_auto_20201219_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPoster1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='media/offerposter1/')),
                ('url', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
