# Generated by Django 3.1.3 on 2021-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0003_offerposter1'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPoster2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='media/offerposter2/')),
                ('url', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
