# Generated by Django 3.1.3 on 2021-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0005_offerposter3'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerposter',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='offerposter1',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='offerposter2',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='offerposter3',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='offerposter1',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
